### ISSUE TITLE
Is is possible to build it on my own device?

### ISSUE THREAD

**Issue by marsrobertson** [nihp-public/covid-19-app-android-ag-public#41]
> To access the private GitHubPackages repository that hosts the remote configurations for all environments

It suggests that I need to access some privatge repositories.

Is there a way for me to build and run it without it?

Or maybe the code presented here is just for public inspection, not for the actual running of the app?

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project - The configuration package is located at https://github.com/nihp-public/covid-19-app-configuration-public - Although it is called "production", it isn't the real production configuration, just a configuration for the production build target.
Due to usage restrictions applied to the Exposure Notification APIs that this system uses, you wouldn't be able to run the app, without making some modifications. Information and guidelines for the EN APIs for Android are located at https://www.google.com/covid19/exposurenotifications/
